#aws cloudformation create-stack --stack-name cloudfront-dps-static --template-body file://cloudfront-dps-static.yaml --capabilities CAPABILITY_NAMED_IAM --parameters file://cloudfront-dps-static-parameters-dev.json --profile dev --region us-east-1
#aws cloudformation update-stack --stack-name cloudfront-dps-static --template-body file://cloudfront-dps-static.yaml --capabilities CAPABILITY_NAMED_IAM --parameters file://cloudfront-dps-static-parameters-dev.json
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Description: env type
    AllowedValues:
      - core
      - dev
      - qa
      - prod
  DomainName:
    Type: String
    Description: Domain Name for the gateway
    Default: dps.boemm.eu
  HostedZoneId:
    Type: String
    Description: route53 zone id
    Default: Z0952617WDGC04ALMM5H

Conditions:
  IsProd: !Equals [ !Ref Environment, "prod"]
  IsDev: !Equals [!Ref Environment, "dev"]
  IsQA: !Equals [!Ref Environment, "qa"]

Resources:
  AcmCertificate:
    Type: AWS::CertificateManager::Certificate
    UpdateReplacePolicy: Delete
    DeletionPolicy: "Retain"
    Properties:
      DomainName: !Join
        - '.'
        - - !If [ IsProd, !Ref "AWS::NoValue", !Ref Environment ]
          - !Sub "${DomainName}"
      SubjectAlternativeNames:
        - !Join
          - '.'
          - - '*'
            - !If [ IsProd, !Ref "AWS::NoValue", !Ref Environment ]
            - !Sub "${DomainName}"
      DomainValidationOptions:
        - DomainName:  !Join
            - '.'
            - - !If [ IsProd, !Ref "AWS::NoValue", !Ref Environment ]
              - !Sub "${DomainName}"
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
  WebAppBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Retain"
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      BucketName: !Join
        - '.'
        - - !If [ IsProd, !Ref "AWS::NoValue", !Ref Environment ]
          - !Sub "${DomainName}"
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
  WebAppBucketPolicy:
    DependsOn: [WebAppBucket, CloudFrontOAI]
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebAppBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Principal:
              AWS:
                - !Join ['', ['arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity', ' ', !Ref CloudFrontOAI]]
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  -  !If [ IsProd, !Ref "AWS::NoValue", !Sub "${Environment}." ]
                  - !Sub "${DomainName}"
                  - '/*'
          - Action:
              - s3:ListBucket
            Effect: Allow
            Principal:
              AWS:
                - "*"
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !If [ IsProd, !Ref "AWS::NoValue", !Sub "${Environment}." ]
                  - !Sub "${DomainName}"
          - Action:
              - s3:GetObject
            Effect: Allow
            Principal: '*'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !If [ IsProd, !Ref "AWS::NoValue", !Sub "${Environment}." ]
                  - !Sub "${DomainName}"
                  - '/*'
            Sid: PublicReadGetObject
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub '${Environment}.${DomainName}.s3.amazonaws.com'
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: '200'
            ResponsePagePath: /index.html
        Origins:
          - DomainName: !Join
              - '.'
              - - !If [ IsProd, !Ref "AWS::NoValue", !Ref Environment ]
                - !Sub "${DomainName}"
                - 's3.amazonaws.com'
            OriginPath: ''
            Id: !Sub 'S3.${DomainName}'
            S3OriginConfig:
              OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOAI]]
        Enabled: 'false'
        Comment: ''
        DefaultRootObject: index.html
        Aliases:
          - !Join
            - '.'
            - - !If [ IsProd, !Ref "AWS::NoValue", !Ref Environment ]
              - !Sub "${DomainName}"
          - !Join
            - '.'
            - - 'www'
              - !If [ IsProd, !Ref "AWS::NoValue", !Ref Environment ]
              - !Sub "${DomainName}"
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - HEAD
            - GET
          TargetOriginId: !Sub 'S3.${DomainName}'
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
            Headers:
              - Authorization
              - Origin
              - Accept
              - Access-Control-Request-Method
              - Access-Control-Request-Headers
              - Referer
              - Set-Cookie
              - X-BOEMM-document-type
              - X-BOEMM-USER
              - Content-Type
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        Restrictions:
          GeoRestriction:
            RestrictionType: none
        HttpVersion: http2
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: 'TLSv1.2_2019'
          AcmCertificateArn: !Ref AcmCertificate
  myDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Join
            - '.'
            - - !If [ IsProd, !Ref "AWS::NoValue", !Ref Environment ]
              - !Sub "${DomainName}"
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt 'Distribution.DomainName'
Outputs:
  Test1:
    Value: !Join ['', ['arn:aws:s3:::', !Ref 'WebAppBucket', /*]]
  Test2:
    Value: !Ref CloudFrontOAI
