name: Build DPS Prod
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  DISTRIBUTION_ID: ${{ vars.DISTRIBUTION_ID }}
  S3_BUCKET_URL: ${{ vars.S3_BUCKET }}
  ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      DPS_VERSION: ${{ steps.getversion.outputs.DPS_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'
          cache: 'npm'

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install dependencies
        continue-on-error: true
        run: |
          npm install -g npm-cli-login
          npm-cli-login -u development..boemm.eu -p "${{ secrets.BRYNTUM_PASS }}" -e development@boemm.eu -r https://npm.bryntum.com
          npm install

      - name: Build application
        run: npm run-script build:prod

      - name: Get Version
        id: getversion
        run: |
          DPS_VERSION=$( npm pkg get version | xargs echo )
          echo "DPS_VERSION=$DPS_VERSION" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: dist
          path: |
            ./dist/dps/browser
          retention-days: 1

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#skip-ci') }}
    environment:
      name: prod
      url: https://dps.boemm.eu
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/Github_Actions_Role
          aws-region: us-east-1

      - name: Retrieve artefact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Upload to S3
        id: upload
        if: github.ref == 'refs/heads/master'
        run: aws s3 sync ./dist ${{ env.S3_BUCKET_URL }} --delete --acl public-read

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ env.DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Retrieve version and Update Param
        run: |
          DPS_VERSION="${{ needs.build.outputs.DPS_VERSION }}"
          echo $DPS_VERSION
          aws ssm put-parameter --name "/dps/clientversion" --type "String" --value "$DPS_VERSION" --overwrite --region eu-central-1
